project:
  type: website
  resources:
    - cv_clw.pdf

website:
  title: "C. Luke Watson"
  site-url: https://clukewatson.github.io
  description: "Financial Economist"
  comments:
    utterances:
      repo: clukewatson/clukewatson.github.io
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Research"
        href: research.html
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml
      - text: "Other People"
        href: people
      - text: "CV"
        href: cv_clw.pdf  
  page-footer:
    left: "© Copyright 2022 C. Luke Watson."
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
